nsl = 199
ndl = 199
ntrg = 199
box = 64
origin = [1,2,3]
kernel = 0 
pbc = 0
seed = 0
eps = 1e-4
max = 2000
direct = false
verify = false
convergence = true
distType = 2
distParam = [-1.0, 0.5]
random = true
wall = false

